<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        // ✅ Sin deletes ni reseed. Idempotente vía updateOrCreate.
        $rows = [
            [
                'code' => 'DGA',
                'name' => 'Diaz Gas',
                'legal_name' => 'Diaz Gas',
                'rfc' => 'DGA930823KD3',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'DCL',
                'name' => 'Distribuidora Clara',
                'legal_name' => 'Distribuidora Clara',
                'rfc' => 'DCL880518UG2',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'DGM',
                'name' => 'Distribuidora Gasomex',
                'legal_name' => 'Distribuidora Gasomex',
                'rfc' => 'DGM880621FU5',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'ECU',
                'name' => 'Estación Custodia',
                'legal_name' => 'Estación Custodia',
                'rfc' => 'ECU0602287R6',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'FGA',
                'name' => 'FormulaGas',
                'legal_name' => 'FormulaGas',
                'rfc' => 'FGA110722PR7',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'GVA',
                'name' => 'Gasolinera Villa Ahumada',
                'legal_name' => 'Gasolinera Villa Ahumada',
                'rfc' => 'GVA9709154V2',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'GOG',
                'name' => 'Grupo Operador Gasolinero TSA del Centro',
                'legal_name' => 'Grupo Operador Gasolinero TSA del Centro',
                'rfc' => 'GOG181220973',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'FIHH',
                'name' => 'Héctor Armandino Fierro Holguín',
                'legal_name' => 'Héctor Armandino Fierro Holguín',
                'rfc' => 'FIHH7303026K7',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'SJA',
                'name' => 'Servicio El Jarudo',
                'legal_name' => 'Servicio El Jarudo',
                'rfc' => 'SJA880518PRA',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'SSY',
                'name' => 'Servicio SYC',
                'legal_name' => 'Servicio SYC',
                'rfc' => 'SSY940520271',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'SGC',
                'name' => 'Servicios Gasolineros El Castaño',
                'legal_name' => 'Servicios Gasolineros El Castaño',
                'rfc' => 'SGC1304129H9',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'SPI',
                'name' => 'SMA Picachos',
                'legal_name' => 'SMA Picachos',
                'rfc' => 'SPI200529SC7',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
            [
                'code' => 'SVE',
                'name' => 'SMA Ventanas',
                'legal_name' => 'SMA Ventanas',
                'rfc' => 'SVE200529DB9',
                'locale' => 'es_MX',
                'timezone' => 'America/Ciudad_Juarez',
                'currency_code' => 'MXN',
                'phone' => '',
                'email' => '',
                'domain' => '',
                'website' => '',
                'logo_path' => '',
                'is_active' => true,
            ],
        ];

        DB::transaction(function () use ($rows) {
            foreach ($rows as $data) {
                Company::updateOrCreate(
                    ['code' => $data['code']], // clave natural única
                    $data
                );
            }
        });
    }
}
